name: Deploy Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install googleapis google-auth-library
        
    - name: Deploy with Service Account
      env:
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        SCRIPT_ID: ${{ secrets.SCRIPT_ID }}
      run: |
        echo $GOOGLE_SERVICE_ACCOUNT_KEY | base64 -d > service-account.json
        echo "Script ID: $SCRIPT_ID"
        node deploy-script.js
      working-directory: ./backend