name: Deploy Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Clasp
        run: npm install -g @google/clasp

      - name: Authenticate Clasp
        env:
          CLASP_JSON: ${{ secrets.CLASP_JSON }}
        run: |
          echo $CLASP_JSON | base64 -d > service-account-key.json
          clasp login --creds service-account-key.json
          rm service-account-key.json

      

      - name: Push to Google Apps Script
        run: clasp push
        working-directory: ./backend
