name: Deploy Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Clasp
        run: npm install -g @google/clasp@2.4.1

      - name: Authenticate Clasp
        env:
          CLASP_AUTH_TOKEN: ${{ secrets.CLASP_AUTH_TOKEN }}
        run: |
          echo $CLASP_AUTH_TOKEN | base64 -d > ~/.clasprc.json

      

      - name: Push to Google Apps Script
        run: clasp push
        working-directory: ./backend
