name: Deploy Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Clasp
        run: npm install -g @google/clasp

      - name: Authenticate Clasp with Service Account
        run: |
          echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > ./gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=./gcp-key.json

      - name: Debug Credentials
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS"
          echo "Files in root directory:"
          ls -la .
          echo "Files in backend directory:"
          ls -la ./backend

      - name: Push to Google Apps Script
        run: clasp push
        working-directory: ./backend
