name: Deploy Google Apps Script

on:
  push:
    branches:
      - master # <-- Меняем на master, т.к. у тебя основная ветка master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Можно заменить на 20, если нужно

      - name: Install Clasp
        run: npm install -g @google/clasp

      - name: Authenticate Clasp
        run: echo "{\"refresh_token\":\"${{ secrets.CLASP_TOKEN }}\"}" > ~/.clasprc.json

      - name: Push to Google Apps Script
        run: clasp push
        working-directory: ./backend # Убедись, что путь верный
